CREATE TABLE `barter_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`barterTxId` varchar(64) NOT NULL,
	`status` enum('proposed','countered','accepted','fee_locked','escrowed','exchanging','verifying','completed','failed','cancelled','disputed','expired') NOT NULL DEFAULT 'proposed',
	`proposerAgentId` varchar(64) NOT NULL,
	`responderAgentId` varchar(64) NOT NULL,
	`offeredPackageId` varchar(128) NOT NULL,
	`requestedPackageId` varchar(128),
	`counterPackageId` varchar(128),
	`offeredAuditId` varchar(128) NOT NULL,
	`requestedAuditId` varchar(128),
	`offeredFmv` decimal(18,6) NOT NULL,
	`requestedFmv` decimal(18,6),
	`fmvDifferencePercent` decimal(5,2),
	`fairnessAcknowledged` boolean NOT NULL DEFAULT false,
	`proposerFeeTon` decimal(18,6),
	`responderFeeTon` decimal(18,6),
	`totalFeeTon` decimal(18,6),
	`proposerFeeTxHash` varchar(128),
	`responderFeeTxHash` varchar(128),
	`feeStatus` enum('pending','proposer_paid','both_paid','refunded') NOT NULL DEFAULT 'pending',
	`escrowKeyShareProposer` text,
	`escrowKeyShareResponder` text,
	`exchangeDeadline` timestamp,
	`proposerVerified` boolean NOT NULL DEFAULT false,
	`responderVerified` boolean NOT NULL DEFAULT false,
	`disputeReason` text,
	`disputeResolution` enum('proposer_wins','responder_wins','split','cancelled'),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `barter_transactions_id` PRIMARY KEY(`id`),
	CONSTRAINT `barter_transactions_barterTxId_unique` UNIQUE(`barterTxId`)
);
--> statement-breakpoint
CREATE TABLE `knowledge_audits` (
	`id` int AUTO_INCREMENT NOT NULL,
	`auditId` varchar(128) NOT NULL,
	`packageId` varchar(128) NOT NULL,
	`packageHash` varchar(128) NOT NULL,
	`qualityScore` int NOT NULL,
	`verdict` enum('approved','conditional','rejected') NOT NULL,
	`fairMarketValue` decimal(18,6) NOT NULL,
	`checks` json NOT NULL,
	`securityFlags` json,
	`platformSignature` text NOT NULL,
	`reviewNotes` text,
	`auditDurationMs` int,
	`expiresAt` timestamp NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `knowledge_audits_id` PRIMARY KEY(`id`),
	CONSTRAINT `knowledge_audits_auditId_unique` UNIQUE(`auditId`)
);
--> statement-breakpoint
CREATE TABLE `knowledge_packages` (
	`id` int AUTO_INCREMENT NOT NULL,
	`packageId` varchar(128) NOT NULL,
	`name` varchar(255) NOT NULL,
	`displayName` varchar(512) NOT NULL,
	`version` varchar(32) NOT NULL,
	`authorAgentId` varchar(64) NOT NULL,
	`description` text,
	`category` varchar(128) NOT NULL,
	`subcategory` varchar(128),
	`proficiencyLevel` enum('beginner','intermediate','advanced','expert') NOT NULL DEFAULT 'intermediate',
	`capabilities` json,
	`prerequisites` json,
	`rootHash` varchar(128) NOT NULL,
	`signature` text NOT NULL,
	`fileSize` int NOT NULL,
	`moduleCount` int NOT NULL,
	`testCount` int NOT NULL,
	`storageUrl` text,
	`auditStatus` enum('pending','in_review','approved','conditional','rejected') NOT NULL DEFAULT 'pending',
	`auditId` varchar(128),
	`isListed` boolean NOT NULL DEFAULT false,
	`listingPrice` decimal(18,6),
	`totalTrades` int NOT NULL DEFAULT 0,
	`totalSales` int NOT NULL DEFAULT 0,
	`avgRating` decimal(3,2) NOT NULL DEFAULT '0.00',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `knowledge_packages_id` PRIMARY KEY(`id`),
	CONSTRAINT `knowledge_packages_packageId_unique` UNIQUE(`packageId`)
);
