/**
 * TON Wallet Authentication Routes
 * 
 * Provides Express endpoints for:
 * - GET  /api/ton-auth/payload  → Generate a nonce for tonProof
 * - POST /api/ton-auth/verify   → Verify tonProof and create session
 * - POST /api/ton-auth/link     → Link wallet to existing account
 */
import { COOKIE_NAME, ONE_YEAR_MS } from "@shared/const";
import type { Express, Request, Response } from "express";
import { nanoid } from "nanoid";
import { getSessionCookieOptions } from "./_core/cookies";
import { createSessionToken, authenticateRequest } from "./_core/sdk";
import * as db from "./db";
import { generatePayload, verifyNonce, verifyTonProof, type TonProofPayload } from "./ton-proof";

/**
 * Get the list of allowed domains for proof verification.
 * Includes the current request's host to support dynamic deployments.
 */
function getAllowedDomains(req: Request): string[] {
  const domains = [
    "nervix.ai",
    "nervix.io",
    "localhost",
    "127.0.0.1",
  ];
  // Add the current host (handles manus.space, custom domains, etc.)
  const host = req.get("host");
  if (host) {
    domains.push(host.split(":")[0]); // strip port
  }
  return domains;
}

export function registerTonAuthRoutes(app: Express) {
  /**
   * GET /api/ton-auth/payload
   * Returns a random payload (nonce) for the client to include in tonProof request.
   */
  app.get("/api/ton-auth/payload", async (_req: Request, res: Response) => {
    try {
      const payload = await generatePayload();
      res.json({ payload });
    } catch (error) {
      console.error("[TonAuth] Failed to generate payload:", error);
      res.status(500).json({ error: "Failed to generate payload" });
    }
  });

  /**
   * POST /api/ton-auth/verify
   * Verifies the tonProof from the wallet and creates a session.
   * 
   * Body: TonProofPayload (address, network, public_key, proof)
   * 
   * Flow:
   * 1. Verify the nonce was generated by us
   * 2. Verify the cryptographic proof (Ed25519 signature)
   * 3. Find or create user by wallet address
   * 4. Create session cookie
   */
  app.post("/api/ton-auth/verify", async (req: Request, res: Response) => {
    try {
      const body = req.body as TonProofPayload;

      if (!body.address || !body.proof || !body.public_key) {
        res.status(400).json({ error: "Missing required fields" });
        return;
      }

      // 1. Verify the nonce
      if (!verifyNonce(body.proof.payload)) {
        res.status(400).json({ error: "Invalid or expired payload nonce" });
        return;
      }

      // 2. Verify the cryptographic proof
      const allowedDomains = getAllowedDomains(req);
      const result = await verifyTonProof(body, allowedDomains);

      if (!result.valid) {
        console.warn("[TonAuth] Proof verification failed:", result.error);
        res.status(401).json({ error: result.error || "Invalid proof" });
        return;
      }

      // 3. Find or create user by wallet address
      const walletAddress = result.address;
      let user = await db.getUserByWalletAddress(walletAddress);

      if (!user) {
        // Create a new user with wallet-based identity
        // Use wallet address as the openId (prefixed to distinguish from email users)
        const openId = `ton_${walletAddress}`;
        const shortAddr = `${walletAddress.slice(0, 6)}...${walletAddress.slice(-4)}`;

        await db.upsertUser({
          openId,
          name: `TON ${shortAddr}`,
          walletAddress,
          tonPublicKey: result.publicKey,
          loginMethod: "telegram_wallet",
          lastSignedIn: new Date(),
        });

        user = await db.getUserByOpenId(openId);
      } else {
        // Update last sign-in and public key
        await db.upsertUser({
          openId: user.openId,
          tonPublicKey: result.publicKey,
          loginMethod: "telegram_wallet",
          lastSignedIn: new Date(),
        });
      }

      if (!user) {
        res.status(500).json({ error: "Failed to create or find user" });
        return;
      }

      // 4. Auto-link wallet to all owned agents
      let linkedAgentIds: string[] = [];
      try {
        linkedAgentIds = await db.propagateWalletToOwnedAgents(user.id, walletAddress);
        if (linkedAgentIds.length > 0) {
          console.log(`[TonAuth] Auto-linked wallet to ${linkedAgentIds.length} agent(s): ${linkedAgentIds.join(", ")}`);
          await db.createAuditEntry({
            eventId: `evt_${nanoid(16)}`,
            eventType: "wallet.auto_linked_agents",
            actorId: user.openId,
            actorType: "system",
            action: `Auto-linked wallet to ${linkedAgentIds.length} agent(s) on login`,
            details: { walletAddress, agentIds: linkedAgentIds },
          });
        }
      } catch (err) {
        console.warn("[TonAuth] Failed to auto-link wallet to agents:", err);
      }

      // 5. Create session cookie
      const sessionToken = await createSessionToken(user.openId, {
        name: user.name || "",
        expiresInMs: ONE_YEAR_MS,
      });

      const cookieOptions = getSessionCookieOptions(req);
      res.cookie(COOKIE_NAME, sessionToken, { ...cookieOptions, maxAge: ONE_YEAR_MS });

      res.json({
        success: true,
        user: {
          id: user.id,
          name: user.name,
          walletAddress: user.walletAddress,
          role: user.role,
        },
        linkedAgents: linkedAgentIds,
      });
    } catch (error) {
      console.error("[TonAuth] Verification failed:", error);
      res.status(500).json({ error: "Verification failed" });
    }
  });

  /**
   * POST /api/ton-auth/link
   * Links a TON wallet to an existing authenticated user account.
   * Requires an active session (user must be logged in).
   * 
   * Body: TonProofPayload
   */
  app.post("/api/ton-auth/link", async (req: Request, res: Response) => {
    try {
      // Verify existing session
      let currentUser;
      try {
        currentUser = await authenticateRequest(req);
      } catch {
        res.status(401).json({ error: "Must be logged in to link wallet" });
        return;
      }

      const body = req.body as TonProofPayload;

      if (!body.address || !body.proof || !body.public_key) {
        res.status(400).json({ error: "Missing required fields" });
        return;
      }

      // Verify the nonce
      if (!verifyNonce(body.proof.payload)) {
        res.status(400).json({ error: "Invalid or expired payload nonce" });
        return;
      }

      // Verify the proof
      const allowedDomains = getAllowedDomains(req);
      const result = await verifyTonProof(body, allowedDomains);

      if (!result.valid) {
        res.status(401).json({ error: result.error || "Invalid proof" });
        return;
      }

      // Check if wallet is already linked to another account
      const existingWalletUser = await db.getUserByWalletAddress(result.address);
      if (existingWalletUser && existingWalletUser.openId !== currentUser.openId) {
        res.status(409).json({ error: "This wallet is already linked to another account" });
        return;
      }

      // Link wallet to current user
      await db.upsertUser({
        openId: currentUser.openId,
        walletAddress: result.address,
        tonPublicKey: result.publicKey,
        lastSignedIn: new Date(),
      });

      // Auto-link wallet to all owned agents
      let linkedAgentIds: string[] = [];
      try {
        const fullUser = await db.getUserByOpenId(currentUser.openId);
        if (fullUser) {
          linkedAgentIds = await db.propagateWalletToOwnedAgents(fullUser.id, result.address);
          if (linkedAgentIds.length > 0) {
            console.log(`[TonAuth] Auto-linked wallet to ${linkedAgentIds.length} agent(s) on link: ${linkedAgentIds.join(", ")}`);
            await db.createAuditEntry({
              eventId: `evt_${nanoid(16)}`,
              eventType: "wallet.auto_linked_agents",
              actorId: currentUser.openId,
              actorType: "system",
              action: `Auto-linked wallet to ${linkedAgentIds.length} agent(s) on wallet link`,
              details: { walletAddress: result.address, agentIds: linkedAgentIds },
            });
          }
        }
      } catch (err) {
        console.warn("[TonAuth] Failed to auto-link wallet to agents on link:", err);
      }

      res.json({
        success: true,
        walletAddress: result.address,
        linkedAgents: linkedAgentIds,
      });
    } catch (error) {
      console.error("[TonAuth] Link failed:", error);
      res.status(500).json({ error: "Failed to link wallet" });
    }
  });
}
